services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doomsday-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.4-alpine
    container_name: doomsday-redis
    ports:
      - "6379:6379"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: doomsday-pg
    environment:
      POSTGRES_USER: doomsday
      POSTGRES_PASSWORD: doomsday
      POSTGRES_DB: doomsday
    ports:
      - "5432:5432"
